organization:
  name: 메가존

app:
  title: 메가존 IDP
  baseUrl: https://backstage.aimegazone.com

backend:
  baseUrl: https://backstage.aimegazone.com
  listen:
    port: 7007
  csp:
    connect-src:
      - "'self'"
      - 'http:'
      - 'https:'
  cors:
    origin: backstage.aimegazone.com
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true

# PG 
  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      password: ${POSTGRES_PASSWORD}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}

# sqlite3 사용시 
#  database:
#    client: better-sqlite3
#    connection: ':memory:'
  # Use this to configure a working directory for the scaffolder, defaults to the OS temp-dir
  # workingDirectory: /Temp


catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, System, Group, Resource, Location, Template, API]
  locations:
  # Note: integrations.github[].apps must be correctly configured to read GitHub locations
    - type: url
      target: https://github.com/jiman94/backstage-megazone/blob/main/catalog-entities/all.yaml
    - type: url
      target: https://github.com/jiman94/backstage-megazone/blob/main/catalog-entities/templates.yaml
    - type: url
      target: https://github.com/jiman94/backstage-megazone/blob/main/catalog-entities/users.yaml
      rules:
        - allow: [User]

  # --------------------------
  # for Local
  # --------------------------
  
    # - type: file
    #   target: ../../catalog-entities/all.yaml
    # - type: file
    #   target: ../../catalog-entities/users.yaml
    #   rules:
    #     - allow: [User]

integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}

proxy:
  endpoints:

techdocs:
  builder: 'local' # Alternatives - 'external'
  #builder: 'external' # Alternatives - 'external'
  generator:
    runIn: 'docker' # Alternatives - 'local'
    #runIn: 'local' # Alternatives - 'local'
  publisher:
    type: 'local' # Alternatives - 'googleGcs' or 'awsS3'. Read documentation for using alternatives.

auth:
  # see https://backstage.io/docs/auth/ to learn about auth providers
  environment: production
  providers:
    github:
      development:
        clientId: ${AUTH_GITHUB_CLIENT_ID}
        clientSecret: ${AUTH_GITHUB_CLIENT_SECRET}

        ## uncomment if using GitHub Enterprise
        # enterpriseInstanceUrl: ${AUTH_GITHUB_ENTERPRISE_INSTANCE_URL}

scaffolder:
  # see https://backstage.io/docs/features/software-templates/configuration for software template options

# Plugin: Argocd

# Plugin: Jenkins

# Plugin: SonarQube


