kind: ConfigMap
apiVersion: v1
metadata:
  name: dev-api-config
  namespace: labide
data:
  application.yaml: |-
    server:
      servlet:
        context-path: /api
      port: 8088
    spring:
      profiles:
        active: dev 
      application:
        name: dev-api-server