kind: ConfigMap
apiVersion: v1
metadata:
  name: dev-api-config
  namespace: backstage
data:
  application.yaml: |-
    spring:
      profiles:
        active: dev 
      application:
        name: dev-api-server