apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-api-server
  namespace: abc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-api-server
  template:
    metadata:
      annotations:
        prometheus.io/path: /api/actuator/prometheus
        prometheus.io/port: "8088"
        prometheus.io/scrape: "true"
      labels:
        app: dev-api-server
    spec:
      serviceAccountName: dev-api-sa
      nodeSelector:
        role: isp
      containers:
        - name: dev-api-server
          image: aaa
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8088
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://tempo-distributed-distributor.tempo.svc:4317
            - name: OTEL_METRICS_EXPORTER
              value: none
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: service.name=dev-api-server
            - name: OTEL_JAVAAGENT_DEBUG
              value: "false"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: dev-api
                  key: DB_DSPA_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dev-api
                  key: DB_DSPA_PASSWORD
            - name: SPRING_DATA_MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: dev-api
                  key: MONGODB_DSPA_URI
            - name: APP_JWT-SECRET
              valueFrom:
                secretKeyRef:
                  name: dev-api
                  key: APP_JWT_SECRET
