apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dev-api-server
  namespace: abc
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dev-api-server
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80