apiVersion: v1
kind: Service
metadata:
  name: backstage-frontend
  namespace: backstage
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: backstage-frontend
---
apiVersion: v1
kind: Service
metadata:
  name: backstage
  namespace: backstage
spec:
  type: NodePort
  ports:
    - port: 7007
      targetPort: 7007
  selector:
    app: backstage